name: tx_gamepad
description: "Client example for the nx Gamepad project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  n_gamepad: ^0.0.6
  t_gamepad:
    git:
      url: https://github.com/nx-gamepad/t_gamepad.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
